// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYjkS63kcOH5A2DWWKA0UnmhGBye2jzW8',
    appId: '1:558025501989:web:3fbe453cbbcf1ec240fecc',
    messagingSenderId: '558025501989',
    projectId: 'fir-79444',
    authDomain: 'fir-79444.firebaseapp.com',
    storageBucket: 'fir-79444.firebasestorage.app',
    measurementId: 'G-09GWK5SKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFHjYWZnJQNf-VNunW6wmVGhy2f0YlL4Q',
    appId: '1:558025501989:android:b72cb9a96b6f50ca40fecc',
    messagingSenderId: '558025501989',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3oRTTeQCp-3D_pLAGPgTcFleKdi3RIFw',
    appId: '1:558025501989:ios:79ef051c6935f8ec40fecc',
    messagingSenderId: '558025501989',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
    iosBundleId: 'com.example.signinExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3oRTTeQCp-3D_pLAGPgTcFleKdi3RIFw',
    appId: '1:558025501989:ios:79ef051c6935f8ec40fecc',
    messagingSenderId: '558025501989',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
    iosBundleId: 'com.example.signinExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYjkS63kcOH5A2DWWKA0UnmhGBye2jzW8',
    appId: '1:558025501989:web:e04cfe4cd2a53ab040fecc',
    messagingSenderId: '558025501989',
    projectId: 'fir-79444',
    authDomain: 'fir-79444.firebaseapp.com',
    storageBucket: 'fir-79444.firebasestorage.app',
    measurementId: 'G-5QVD8Q1PZ7',
  );
}
